# Generated by Django 4.2.5 on 2023-09-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jokoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('deskribapena', models.TextField()),
                ('kategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Egilea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('emaila', models.CharField(max_length=100)),
                ('jokoak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.jokoa')),
            ],
        ),
    ]
