# Generated by Django 4.2.5 on 2023-09-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egilea',
            name='jokoak',
        ),
        migrations.AddField(
            model_name='jokoa',
            name='egilea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.egilea'),
            preserve_default=False,
        ),
    ]
